### ISSUE TITLE
add icon for Lollypop

### ISSUE THREAD

**Issue by WebFreak001** [FichteFoll/discordrp-mpris#15]
Lollypop is a modern music player for GNOME

https://wiki.gnome.org/Apps/Lollypop

Logo: ![Lollypop logo](https://gitlab.gnome.org/World/lollypop/-/raw/master/data/icons/hicolor/512x512/apps/org.gnome.Lollypop.png)

**Comment by FichteFoll** [comment]
Thanks, I'll add this when I work on the next iteration. No ETA, unfortunately.
