### ISSUE TITLE
Discord Flatpak

### ISSUE THREAD

**Issue by Atrate** [FichteFoll/discordrp-mpris#17]
Hey there!

I think it may be useful if the README included instruction on how to make Discord connect to drp-mpris when Discord is installed through Flatpak.

Atrate

**Comment by FichteFoll** [comment]
If someone who uses discord vial flatpak would provide some instructions or submit them as a pull request, I would be glad to add that.

**Comment by Atrate** [comment]
I use Discord through Flatpak and have so far had no success getting it to work.

Background: Flatpak does not let processes discover other running processes, and there is no workaround: https://github.com/flathub/com.discordapp.Discord/issues/11 .

It is possible to allow a Flatpak application to access the following features, though:
- IPC (`share=ipc`)
- D-Bus Session Bus (`socket=session-bus`)
- D-Bus System Bus (`socket=system-bus`)

As well as specified names on the system and session buses (divided by "talks" and "owns).

So far, I've enabled Discord to use IPC, the Session and System buses and I've had no luck. What name does drp-mpris use on the session/system bus?

**Comment by FichteFoll** [comment]
We communicate with Discord over the UNIX Domain Socket it provides in a temporary directory.

https://github.com/FichteFoll/discordrp-mpris/blob/bef1f306fcfbb8f88c2c89d4851e6581db4f2bbe/discord_rpc/async_.py#L216-L224

**Comment by Atrate** [comment]
The Discord Socket when Discord is ran in Flatpak can be found here:
```
$XDG_RUNTIME_DIR/app/com.discordapp.Discord/discord-ipc-0
```

**Comment by FichteFoll** [comment]
That's fine, I can work with this. I need to add snap support as well, as I have done somewhere else already.
