### ISSUE TITLE
No config file on Arch

### ISSUE THREAD

**Issue by rdricco** [FichteFoll/discordrp-mpris#21]
I cannot find the config file on Arch (installed via aur). Can you help me? 
Do I need to manually create?
Thanks in advance.

**Comment by FichteFoll** [comment]
You can list a package's files with the following command, which will, among others, include the default config file:
```
$ pacman -Ql discordrp-mpris-git  
…
discordrp-mpris-git /usr/lib/python3.9/site-packages/discordrp_mpris/config/config.toml
```

To adjust the configuration for your own, however, as mentioned [in the README](https://github.com/FichteFoll/discordrp-mpris#configuration). You'll need to create the file if you didn't already.
