### ISSUE TITLE
Failed to connect to Discord client

### ISSUE THREAD

**Issue by rdricco** [FichteFoll/discordrp-mpris#23]
Cannot connect to discord after last update.

`DEBUG:discord_rpc.async_:'/run/user/1000/discord-ipc-2' not found`
`DEBUG:discord_rpc.async_:'/run/user/1000/discord-ipc-3' not found`
`DEBUG:discord_rpc.async_:'/run/user/1000/discord-ipc-4' not found`
`DEBUG:discord_rpc.async_:'/run/user/1000/discord-ipc-5' not found`
`DEBUG:discord_rpc.async_:'/run/user/1000/discord-ipc-6' not found`
`DEBUG:discord_rpc.async_:'/run/user/1000/discord-ipc-7' not found`
`DEBUG:discord_rpc.async_:'/run/user/1000/discord-ipc-8' not found`
`DEBUG:discord_rpc.async_:'/run/user/1000/discord-ipc-9' not found`
`DEBUG:discordrp_mpris.__main__:Failed to connect to Discord client`
`DEBUG:discordrp_mpris.config:Value for 'global.reconnect_wait': 1`

**Comment by rdricco** [comment]
Looks like it solved alone. Maybe it was a problem on discord side.

**Comment by FichteFoll** [comment]
Connection problems can be triggerd by a variety of reasons. I intend to make reconnecting more robust, which should alleviate the pain.
