### ISSUE TITLE
Manual installation refers to the wrong link

### ISSUE THREAD

**Issue by jojo2357** [FichteFoll/discordrp-mpris#27]
In the readme, there is a [manual installation option](https://github.com/FichteFoll/discordrp-mpris#manual), but this link did not work:

`https://github.com/FichteFoll/discordrp-mpris`

but when i used the zip of the latest release:

`https://github.com/FichteFoll/discordrp-mpris/archive/refs/tags/v0.3.2.zip`

it worked as intended. I also wonder why `systemctl --user enable discordrp-mpris.service --now` does not work when I do it that way. Right now i open a terminal to run the rich presence, but I would like it to be automatic. Should I set up a cron job to do it or is there a better way?

**Comment by FichteFoll** [comment]
Thanks for the heads-up, I fixed the installation commands in a1374a80dcfb33a297cda85155dc126ce84ff113.

When you use manual installation, the [systemd unit file](https://github.com/FichteFoll/discordrp-mpris/blob/a1374a80dcfb33a297cda85155dc126ce84ff113/systemd/discordrp-mpris.service) isn't copied to the proper location where systemd expects it. You will need to copy/create it yourself at `~/.config/systemd/user` first. Then you can control it like any other unit file installed to your system. Note that you will most likely also need to update the executable path to `/home/<your_user>/.local/bin/discordrp-mpris`, unless you installed as root.
