### ISSUE TITLE
Cannot block Mozilla Firefox

### ISSUE THREAD

**Issue by DontEvenTalkToMe** [FichteFoll/discordrp-mpris#39]
Hello so I've made a folder(/home/$USER/.config/discordrp-mpris), however when I place in the config.toml and I changed [player.Spotify] to [player.Mozilla firefox] However this blocks all media players including Strawberry(the one I want to use). I also tried player.Mozilla, player.Mozilla.firefox, player.Firefox and player.Mozilla-firefox and while they don't block Strawberry, they don't block Firefox. I'm sure I'm doing something stupid but some help would be great. I'm on python 3.12, Arch(btw) and KDE Plasma if that matters.

**Comment by FichteFoll** [comment]
See also https://github.com/FichteFoll/discordrp-mpris/issues/37.

It has to be `[player."Mozilla Firefox"]`. It is admittedly one of the weirdest quirks of TOML, but with the improved default configuration (that hasn't been released yet) it should be much clearer how to use it.
