### ISSUE TITLE
mpc-qt support

### ISSUE THREAD

**Issue by BobbyWibowo** [FichteFoll/discordrp-mpris#6]
Hi there, thanks for the great job.
It's been working pretty well with mpv and others, but I'm having some issues with [mpc-qt](https://github.com/cmdrkotori/mpc-qt).

First, on any tracks, their "artist" will always be a string instead of a list of strings. So the current code will end up joining every character of the string with `&` (e.i. `Jack` becomes `J & a & c & k`). Adding a little patch, where it will add the value into a list IF its type is a string, fixed the issue for me (on a side note I'm not too familiar with Python so please excuse me if my phrasing sound odd or something).

Second, mpc-qt seem to update its mpris thingy every second even if it's still playing the same track, so the elapsed time status in Discord will always reset back to 00.00 after a few seconds.
I noticed the same behavior with other project (not mine) that would also monitor mpris. Basically it would report that mpc-qt would keep on updating its track position every second, but it wouldn't report anything like that for any other players (including mpv) even when I tried to manually seek other position. Then again I don't really understand this whole mpris thingy either.

**Comment by BobbyWibowo** [comment]
It doesn't have any fancy icon that I'm aware of. At the moment it's using [this icon](https://github.com/cmdrkotori/mpc-qt/blob/master/images/icon/mpc-qt.svg), including for the occasional Windows releases (it's an SVG though, so you may have to manually make a PNG version or something?). I think I'd also prefer having that icon used instead.

**Comment by BobbyWibowo** [comment]
Hi again, so I happened to be free and wanted to look more into it. I managed to figure out the issue. For mpc-qt, its position timestamp will always be in milliseconds instead of microseconds, so it'll always be converted to 00:00. Thus adding a patch where its position will be multiplied by 1000 if the active player is mpc-qt would solve it.
It feels kinda awkward having a special treatment for it tho, but oh well.
Here's some sneak peeks:
![Playing](https://i.fiery.me/JFyw.png) ![Paused](https://i.fiery.me/lW36.png)
(kinda ended up making my own Discord app to have mpc-qt logo)

**Comment by FichteFoll** [comment]
>At the moment it's using this icon

I'll take it.

>its position timestamp will always be in milliseconds instead of microseconds

Ah well, that was unexpected. I submitted a PR upstream so I don't have to add a workaround myself, since I could run into issues when that gets fixed and I still have the workaround in place. See https://github.com/cmdrkotori/mpc-qt/pull/203. Hopefully that'll get released fast enough for people using it (assuming they're not on debian or something).

**Comment by FichteFoll** [comment]
Both your mentioned issues are fixed upstream. You'll need a version built from master to use them, of course. I declared support for mpc-qt in 1d944c696e29e09e8ccae3a82bb97cf4e3c31f96 and added an icon to my app.
